'use strict';

const { z } = require('zod');

// Student client creates session: enters durationMinutes only.
// Disallows startTime, expectedEndTime and actualEndTime —
// all timing fields are generated by the backend server clock.
const createSessionSchema = z.object({
  localId: z.string().min(1, 'localId is required').max(100),
  registrationNo: z.string().min(1, 'registrationNo is required').max(50),
  name: z.string().min(1, 'name is required').max(100),
  department: z.string().min(1, 'department is required').max(100),
  section: z.string().min(1, 'section is required').max(10),
  year: z.number({ required_error: 'year is required' }).int().min(1).max(5),
  durationMinutes: z
    .number({ required_error: 'durationMinutes is required' })
    .int()
    .min(1, 'durationMinutes must be at least 1')
    .max(480, 'durationMinutes cannot exceed 480 (8 hours)'),
  systemCode: z.string().min(1, 'systemCode is required').max(50),
  faculty: z.string().max(100).optional().nullable(),
  ipAddress: z.string().max(50).optional().nullable(),
  // startTime is intentionally NOT accepted here.
  // Backend always generates startTime from server clock at session creation.
  // Client-provided startTime is only accepted through the offline sync route.
}).strict({
  message:
    'Unexpected fields provided. startTime, expectedEndTime, and actualEndTime are system-generated and cannot be submitted by the client.',
});

// Offline sync session schema
const syncSessionSchema = z.object({
  localId: z.string().min(1).max(100),
  registrationNo: z.string().min(1).max(50),
  name: z.string().min(1).max(100),
  department: z.string().min(1).max(100),
  section: z.string().min(1).max(10),
  year: z.number().int().min(1).max(5),
  durationMinutes: z.number().int().min(1).max(480),
  systemCode: z.string().min(1).max(50),
  faculty: z.string().max(100).optional().nullable(),
  ipAddress: z.string().max(50).optional().nullable(),
  startTime: z.string().refine((v) => !isNaN(Date.parse(v)), {
    message: 'startTime must be a valid ISO 8601 datetime string',
  }),
  actualEndTime: z.string().refine((v) => !isNaN(Date.parse(v)), {
    message: 'actualEndTime must be a valid ISO 8601 datetime string',
  }).optional().nullable(),
  status: z.enum(['ACTIVE', 'COMPLETED', 'EXPIRED', 'CANCELLED']).optional(),
});

const syncBatchSchema = z.object({
  sessions: z
    .array(syncSessionSchema)
    .min(1, 'At least one session is required')
    .max(500, 'Maximum 500 sessions per sync batch'),
});

module.exports = {
  createSessionSchema,
  syncSessionSchema,
  syncBatchSchema,
  syncSessionsBatchSchema: syncBatchSchema,
};
